### ISSUE TITLE
wrong view

### ISSUE THREAD

**Issue by fiorins** [hiatus-hiatus/hiatus-hiatus.github.io#4]
Hi! I would like to create my own chart, but why does the site not display it correctly?

<img width="1280" alt="Screenshot 2021-01-18 at 01 46 52" src="https://user-images.githubusercontent.com/32281481/104861195-268c5c80-592f-11eb-9584-ae20cedd10e5.png">

**Comment by julianotoriani** [comment]
How are you accessing the page? You need to serve the root directory through a server.

By the screenshot it seems VueJS is failing to load in your browser.

**Comment by fiorins** [comment]
I fork this repository and then I change github page link because I would just like to reproduce the repository and create a table with my series and that it is accessible from the github page like this, I hope you can help me

**Comment by fiorins** [comment]
Which server ?

**Comment by julianotoriani** [comment]
It's hard to say what's going wrong without knowing how you got to that page in the screenshot.

And indeed, for the page to load properly in your local environment you need to serve the root directory through an http server.

If you're on linux it should be as easy as running  `python -m http.server` on the root directory of the project (the one that contains the index.html and app.js files).

The output should be similar to this:

    $ python -m http.server               
    Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...


Then you can open http://localhost:8000/ in a browser.

**Comment by rentzhx3** [comment]
Sorry, posting again because I replied on my other account earlier.

It's hard to say what's going wrong without knowing how you got to that page in the screenshot.

And indeed, for the page to load properly in your local environment you need to serve the root directory through an http server.

If you're on linux it should be as easy as running  `python -m http.server` on the root directory of the project (the one that contains the index.html and app.js files).

The output should be similar to this:

    $ python -m http.server               
    Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...


Then you can open http://localhost:8000/ in a browser.

**Comment by fiorins** [comment]
Ok thanks, I finally solved using another software
